## Q3: Are you faster than numpy?

Numpy of course has a standard deviation function, `np.std()`, but here we'll write our own that works on a 1-d array (vector).  The standard
deviation is a measure of the "width" of the distribution of numbers
in the vector.

Given an array, $a$, and an average $\bar{a}$, the standard deviation
is:
$$
\sigma = \left [ \frac{1}{N} \sum_{i=1}^N (a_i - \bar{a})^2 \right ]^{1/2}
$$

Write a function to calculate the standard deviation for an input array, `a`:

  * First compute the average of the elements in `a` to define $\bar{a}$
  * Next compute the sum over the squares of $a - \bar{a}$
  * Then divide the sum by the number of elements in the array
  * Finally take the square root (you can use `np.sqrt()`)
  
Test your function on a random array, and compare to the built-in `np.std()`. Check the runtime as well.

In [2]:
import numpy as np
import time

In [14]:
ndim = int(1e6)
a = np.random.rand(ndim)
n_rep = int(1e3)

def my_std(a):
    return np.sqrt(np.sum((a - np.mean(a)) ** 2) / len(a))

#################
### My method ###
#################
t0_my = time.time()
for i in range(n_rep):
    std = my_std(a)
t1_my = time.time()
print(f"'My method' time elapsed:   {(t1_my - t0_my)/n_rep*1e3:.5f} ms,   std = {std}")

#############
### Numpy ###
#############
t0_np = time.time()
for i in range(n_rep):
    np_std = np.std(a)
t1_np = time.time()
print(f"'Numpy' time elapsed:       {(t1_np - t0_np)/n_rep*1e3:.5f} ms,   std = {np_std}")

'My method' time elapsed:   0.96735 ms,   std = 0.2885670149785703
'Numpy' time elapsed:       1.04568 ms,   std = 0.2885670149785703


## Q5: Einstein summation

einsum is a powerful (but often painful) numpy thing:
- https://numpy.org/doc/stable/reference/generated/numpy.einsum.html
- https://stackoverflow.com/questions/26089893/understanding-numpys-einsum

Take 2 vectors A and B. Write the einsum equivalent of inner, outer, sum, and mul function.

In [27]:
A = np.random.rand(10)
B = np.random.rand(10)

### inner ###
print(f'inner  :  einsum = {np.einsum("i,i", A, B)}, numpy = {np.inner(A, B)}\n') # A_i B_i 

### outer ###
print(f'outer  :  einsum - numpy = \n{np.einsum("i,j", A, B) - np.outer(A, B)}\n') # A_i B_j = C_ij, should be equal to 0 matrix. 

### sum ### 
print(f'sum A  :  numpy = {np.sum(A)}, einsum = {np.einsum("i->", A)}')
print(f'sum B  :  numpy = {np.sum(B)}, einsum = {np.einsum("i->", B)}\n')

### matmul ###
A = np.random.rand(10, 10)
B = np.random.rand(10, 10)

print(f'matmul  :  numpy - einsum = \n{np.matmul(A, B) - np.einsum("ij,jk->ik", A, B)}\n')

inner  :  einsum = 1.888865669319837, numpy = 1.8888656693198371

outer  :  einsum - numpy = 
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]

sum A  :  numpy = 3.984727665436452, einsum = 3.984727665436452
sum B  :  numpy = 5.6416475474977075, einsum = 5.641647547497707

matmul  :  numpy - einsum = 
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]

