In [1]:
import numpy as np

## Q5: Einstein summation

einsum is a powerful (but often painful) numpy thing:
- https://numpy.org/doc/stable/reference/generated/numpy.einsum.html
- https://stackoverflow.com/questions/26089893/understanding-numpys-einsum

Take 2 vectors A and B. Write the einsum equivalent of inner, outer, sum, and mul function.

In [2]:
A = np.random.rand(10)
B = np.random.rand(10)

### inner ###
print(f'inner  :  einsum = {np.einsum("i,i", A, B)}, numpy = {np.inner(A, B)}\n') # A_i B_i 

### outer ###
print(f'outer  :  einsum - numpy = \n{np.einsum("i,j", A, B) - np.outer(A, B)}\n') # A_i B_j = C_ij, should be equal to 0 matrix. 

### sum ### 
print(f'sum A  :  numpy = {np.sum(A)}, einsum = {np.einsum("i->", A)}')
print(f'sum B  :  numpy = {np.sum(B)}, einsum = {np.einsum("i->", B)}\n')

### matmul ###
A = np.random.rand(10, 10)
B = np.random.rand(10, 10)

print(f'matmul  :  numpy - einsum = \n{np.matmul(A, B) - np.einsum("ij,jk->ik", A, B)}\n')

inner  :  einsum = 1.9161957081950587, numpy = 1.9161957081950591

outer  :  einsum - numpy = 
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]

sum A  :  numpy = 5.043069328174349, einsum = 5.043069328174347
sum B  :  numpy = 4.097499860307841, einsum = 4.097499860307841

matmul  :  numpy - einsum = 
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]



## Q6: Conway's Game of Life

**Exercise**: Code up Conway's Game of Life using numpy 

The Game of Life is a cellular automaton devised by mathematician John Horton Conway in 1970. It is a zero-player game, meaning that its evolution is determined by its initial state, requiring no further input. One interacts with the Game of Life by creating an initial configuration and observing how it evolves. It is Turing complete and can simulate a universal constructor or any other Turing machine.

https://en.wikipedia.org/wiki/Conway%27s_Game_of_Life

The Game of Life is *really* (really, really) cool. There are just four extremely simple rules, and these result in an immense richness of behaviour and complexity.

https://www.youtube.com/watch?v=C2vgICfQawE&t=221s&ab_channel=RationalAnimations

https://www.youtube.com/watch?v=jvSp6VHt_Pc&ab_channel=TheDevDoctor

Here some web apps to play:

https://conwaylife.com/

https://playgameoflife.com/

Some computational hints:

https://blog.datawrapper.de/game-of-life/

For instance, here is a Game-of-Life structure that sends a message at fixed intervals (that little spaceship leaving toward the bottom right)

![](https://blog.datawrapper.de/wp-content/uploads/2021/06/game-of-life-loop-cropped.gif)


<strong> Check file <code>game_of_life.py</code> for both the solutions of Q6 of this lecture and the corrisponding animation of Q8 of lecture L03. </strong>.

Execute the script digiting: <code>$ python3 game_of_life.py</code> or you can import the module and call the method <code>.play()</code> with different initial parameters to change the grid dimension, the number of frames of the animation and the initial state. 